
builtin_types_and_functions = {
    "abs": abs,
    "all": all,
    "any": any,
    "bool": bool,
    "chr": chr,
    "dict": dict,
    "divmod": divmod,
    "enumerate": enumerate,
    "filter": filter,
    "float": float,
    "int": int,
    "len": len,
    "list": list,
    "map": map,
    "max": max,
    "min": min,
    "pow": pow,
    "range": range,
    "round": round,
    "reversed": reversed,
    "set": set,
    "sorted": sorted,
    "sum": sum,
    "str": str,
    "tuple": tuple,
    "zip": zip
}