# Generated by Django 4.2.1 on 2023-06-09 08:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_pricing_structure_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingmodel",
            name="pricing_structure_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="featurerepository",
            name="product_id",
            field=models.ForeignKey(
                db_column="product_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_repositories",
                to="api.product",
            ),
        ),
        migrations.AlterField(
            model_name="pricingmodel",
            name="package_id",
            field=models.ForeignKey(
                db_column="package_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_model_package_details",
                to="api.package",
            ),
        ),
        migrations.AlterField(
            model_name="pricingmodeldetails",
            name="pricing_model_id",
            field=models.ForeignKey(
                db_column="pricing_model_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_model_id_details",
                to="api.pricingmodel",
            ),
        ),
        migrations.AlterField(
            model_name="pricingmodeldetails",
            name="tier_id",
            field=models.ForeignKey(
                db_column="tier_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_model_details_tier",
                to="api.tier",
            ),
        ),
        migrations.AlterField(
            model_name="pricingstructure",
            name="pricing_model_id",
            field=models.ForeignKey(
                db_column="pricing_model_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_model_custom_structure",
                to="api.pricingmodel",
            ),
        ),
        migrations.AlterField(
            model_name="tier",
            name="plan_id",
            field=models.ForeignKey(
                db_column="plan_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.plan",
            ),
        ),
        migrations.CreateModel(
            name="PricingMetricMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "pricing_metrics_id",
                    models.ForeignKey(
                        db_column="pricing_metrics_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_metric_model_id",
                        to="api.pricingmetric",
                    ),
                ),
                (
                    "pricing_model_id",
                    models.ForeignKey(
                        db_column="pricing_model_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_metric_model_id",
                        to="api.pricingmodel",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_metric_mapping",
            },
        ),
    ]
