# Generated by Django 4.2.1 on 2023-06-19 14:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_feature_tenant_id_featuregroup_tenant_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "pricebook",
            },
        ),
        migrations.CreateModel(
            name="PriceBookRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "opportunity_type_id",
                    models.ForeignKey(
                        db_column="package_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.opportunitytype",
                    ),
                ),
                (
                    "price_book_id",
                    models.ForeignKey(
                        db_column="price_book_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.pricebook",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "pricebook_rule",
            },
        ),
        migrations.CreateModel(
            name="PriceBookEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "package_id",
                    models.ForeignKey(
                        db_column="package_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.package",
                    ),
                ),
                (
                    "plan_id",
                    models.ForeignKey(
                        db_column="plan_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.plan",
                    ),
                ),
                (
                    "price_book_id",
                    models.ForeignKey(
                        db_column="price_book_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.pricebook",
                    ),
                ),
                (
                    "pricing_model_id",
                    models.ForeignKey(
                        db_column="pricing_model_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.pricingmodel",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.product",
                    ),
                ),
            ],
            options={
                "db_table": "pricebook_entry",
            },
        ),
        migrations.CreateModel(
            name="PriceBookDiscountPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("details", models.JSONField()),
                (
                    "price_book_id",
                    models.ForeignKey(
                        db_column="price_book_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.pricebook",
                    ),
                ),
            ],
            options={
                "db_table": "pricebook_discount_policy",
            },
        ),
    ]
