# Generated by Django 4.2.1 on 2023-06-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_pricebook_pricebookrule_pricebookentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="tenant_id",
            field=models.ForeignKey(
                db_column="tenant_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.tenant",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="tenant_id",
            field=models.ForeignKey(
                db_column="tenant_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.tenant",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="tenant_id",
            field=models.ForeignKey(
                db_column="tenant_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.tenant",
            ),
        ),
        migrations.AddField(
            model_name="opportunitystage",
            name="tenant_id",
            field=models.ForeignKey(
                db_column="tenant_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.tenant",
            ),
        ),
        migrations.AddField(
            model_name="opportunitytype",
            name="tenant_id",
            field=models.ForeignKey(
                db_column="tenant_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.tenant",
            ),
        ),
        migrations.AddField(
            model_name="pricebook",
            name="tenant_id",
            field=models.ForeignKey(
                db_column="tenant_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.tenant",
            ),
        ),
        migrations.AddField(
            model_name="pricebookdiscountpolicy",
            name="tenant_id",
            field=models.ForeignKey(
                db_column="tenant_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.tenant",
            ),
        ),
        migrations.AddField(
            model_name="pricebookentry",
            name="tenant_id",
            field=models.ForeignKey(
                db_column="tenant_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.tenant",
            ),
        ),
        migrations.AddField(
            model_name="pricebookrule",
            name="tenant_id",
            field=models.ForeignKey(
                db_column="tenant_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.tenant",
            ),
        ),
    ]
