# Generated by Django 4.2.1 on 2023-06-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_pricing_str_reformart1"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="created_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="owner_id",
            field=models.ForeignKey(
                db_column="owner_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.user",
            ),
        ),
    ]
