# Generated by Django 4.2.1 on 2023-06-29 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_orghierarchy_id_ext_key_and_more"),
        ("api", "0012_salesforcemappingmodel"),
    ]

    operations = []
