# Generated by Django 4.2.1 on 2023-06-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_opportunity_created_date_alter_opportunity_owner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="op_external_id",
            field=models.TextField(null=True),
        ),
    ]
