# Generated by Django 4.2.1 on 2023-06-29 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_merge_20230629_0855"),
        ("api", "0014_alter_pricebookrule_opportunity_type_id"),
    ]

    operations = []
