# Generated by Django 4.2.1 on 2023-06-30 08:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_merge_20230629_1330"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.CharField(max_length=100)),
                (
                    "opportunity_id",
                    models.ForeignKey(
                        db_column="opportunity_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.opportunity",
                    ),
                ),
                (
                    "pricebook_id",
                    models.ForeignKey(
                        db_column="pricebook_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pricebook",
                    ),
                ),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "quote",
            },
        ),
        migrations.CreateModel(
            name="QuoteNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("comment", models.CharField(max_length=100)),
                (
                    "quote_id",
                    models.ForeignKey(
                        db_column="quote_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.quote",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "quote_note",
            },
        ),
        migrations.CreateModel(
            name="QuoteDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.JSONField()),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
                (
                    "quote_id",
                    models.ForeignKey(
                        db_column="quote_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.quote",
                    ),
                ),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
                (
                    "tier_id",
                    models.ForeignKey(
                        db_column="tier_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.tier",
                    ),
                ),
            ],
            options={
                "db_table": "quote_details",
            },
        ),
    ]
