# Generated by Django 4.2.1 on 2023-07-03 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_quote_quotenote_quotedetails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="version",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="quotedetails",
            old_name="version",
            new_name="details",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="pricebook_id",
        ),
        migrations.AddField(
            model_name="quote",
            name="price_book_id",
            field=models.ForeignKey(
                db_column="price_book_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.pricebook",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="opportunity_id",
            field=models.ForeignKey(
                db_column="opportunity_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.opportunity",
            ),
        ),
    ]
