# Generated by Django 4.2.1 on 2023-07-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_rename_version_quote_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="external_description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="feature",
            name="external_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="featuregroup",
            name="external_description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="featuregroup",
            name="external_name",
            field=models.CharField(max_length=255, null=True),
        )
    ]
