# Generated by Django 4.2.1 on 2023-07-10 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_pricing_structure_reformat_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                ("method", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "feature_list",
            },
        ),
        migrations.AlterField(
            model_name="quote",
            name="tenant_id",
            field=models.ForeignKey(
                db_column="tenant_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.tenant",
            ),
        ),
        migrations.CreateModel(
            name="UserFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "feature_list_id",
                    models.ForeignKey(
                        db_column="feature_list_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.featurelist",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_feature",
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="RoleFeatureMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "feature_list_id",
                    models.ForeignKey(
                        db_column="feature_list_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.featurelist",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.roles",
                    ),
                ),
            ],
            options={
                "db_table": "role_feature_mapping",
            },
        ),
    ]
