# Generated by Django 4.2.1 on 2023-07-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_featurelist_alter_quote_tenant_id_userfeature_roles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rolefeaturemapping",
            name="role_id",
        ),
        migrations.AddField(
            model_name="rolefeaturemapping",
            name="user_role_id",
            field=models.ForeignKey(
                db_column="user_role_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.userrole",
            ),
        ),
        migrations.DeleteModel(
            name="Roles",
        ),
    ]
