# Generated by Django 4.2.1 on 2023-07-12 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_quote_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_role_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_role_id_ext_key",
        ),
        migrations.CreateModel(
            name="UserRoleMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.user",
                    ),
                ),
                (
                    "user_role_id",
                    models.ForeignKey(
                        db_column="user_role_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.userrole",
                    ),
                ),
            ],
            options={
                "db_table": "user_role_map",
            },
        ),
    ]
