# Generated by Django 4.2.1 on 2023-07-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_remove_user_user_role_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.user",
            ),
        ),
    ]
