# Generated by Django 4.2.1 on 2023-07-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_quote_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(default="draft", max_length=100),
        ),
    ]
