# Generated by Django 4.2.1 on 2023-07-17 07:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_alter_quote_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="number",
            new_name="account_number",
        ),
        migrations.RemoveField(
            model_name="account",
            name="account_ext_key",
        ),
        migrations.RemoveField(
            model_name="account",
            name="billing_address_id",
        ),
        migrations.RemoveField(
            model_name="account",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="account",
            name="shipping_address_id",
        ),
        migrations.AddField(
            model_name="account",
            name="account_ext_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="billing_city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="billing_country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="billing_postal_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="billing_state",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="billing_street",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_created_by",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="custom_field_1",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="custom_field_2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="custom_field_3",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="custom_field_4",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="shipping_city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="shipping_country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="shipping_postal_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="shipping_state",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="shipping_street",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="updated_by",
            field=models.ForeignKey(
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_updated_by",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunity_created_by",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="custom_field_1",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="custom_field_2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="custom_field_3",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="custom_field_4",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="updated_by",
            field=models.ForeignKey(
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunity_updated_by",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="account_id",
            field=models.ForeignKey(
                db_column="account_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.account",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="custom_field_1",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="custom_field_2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="custom_field_3",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="custom_field_4",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="quote",
            name="quote_external_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="quote_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="quote_url",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_created_by",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="custom_field_1",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="custom_field_2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="custom_field_3",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="custom_field_4",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_by",
            field=models.ForeignKey(
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_updated_by",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="userrolemapping",
            name="is_salesforce",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="annual_revenue",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="funding_amount",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="no_of_employees",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="owner_id",
            field=models.ForeignKey(
                db_column="owner_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_owner",
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="ownership",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="upsell_opportunity",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="year_started",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="account_id",
            field=models.ForeignKey(
                db_column="account_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_id",
                to="api.account",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="amount",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="close_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="contract_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="contract_link",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="op_external_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="probability",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="stage_id",
            field=models.ForeignKey(
                db_column="stage_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.opportunitystage",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="type_id",
            field=models.ForeignKey(
                db_column="type_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.opportunitytype",
            ),
        ),
        migrations.CreateModel(
            name="IndustryType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "industry_type",
            },
        ),
        migrations.CreateModel(
            name="ContractStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "contract_status",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("contract_number", models.CharField(max_length=255)),
                ("company_signed_date", models.DateTimeField(null=True)),
                ("activated_date", models.DateTimeField(null=True)),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("customer_signed_id", models.CharField(max_length=255)),
                ("customer_signed_date", models.DateTimeField(null=True)),
                ("customer_signed_title", models.CharField(max_length=255)),
                ("billing_street", models.TextField(null=True)),
                ("billing_city", models.CharField(max_length=255, null=True)),
                ("billing_state", models.CharField(max_length=255, null=True)),
                ("billing_postal_code", models.CharField(max_length=255, null=True)),
                ("billing_country", models.CharField(max_length=255, null=True)),
                ("shipping_street", models.TextField(null=True)),
                ("shipping_city", models.CharField(max_length=255, null=True)),
                ("shipping_state", models.CharField(max_length=255, null=True)),
                ("shipping_postal_code", models.CharField(max_length=255, null=True)),
                ("shipping_country", models.CharField(max_length=255, null=True)),
                ("special_terms", models.TextField(null=True)),
                ("close_date", models.DateTimeField(null=True)),
                ("created_date", models.DateField(null=True)),
                ("contract_external_id", models.CharField(max_length=255, null=True)),
                ("contract_url", models.CharField(max_length=255, null=True)),
                ("custom_field_1", models.CharField(max_length=255, null=True)),
                ("custom_field_2", models.CharField(max_length=255, null=True)),
                ("custom_field_3", models.TextField(max_length=255, null=True)),
                ("custom_field_4", models.CharField(max_length=255, null=True)),
                (
                    "account_id",
                    models.ForeignKey(
                        db_column="account_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_account_id",
                        to="api.account",
                    ),
                ),
                (
                    "company_signed_id",
                    models.ForeignKey(
                        db_column="company_signed_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.user",
                    ),
                ),
                (
                    "contract_status_id",
                    models.ForeignKey(
                        db_column="contract_status_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.contractstatus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_created_by",
                        to="api.user",
                    ),
                ),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_updated_by",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "contract",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="industry_type_id",
            field=models.ForeignKey(
                db_column="industry_type_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_industry_type",
                to="api.industrytype",
            ),
        ),
    ]
