# Generated by Django 4.2.1 on 2023-07-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_salesforce_schema_changes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orghierarchy",
            name="description",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
