# Generated by Django 4.2.1 on 2023-07-18 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_alter_opportunity_close_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="assigned_to",
            field=models.ForeignKey(
                db_column="assigned_to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.user",
            ),
        ),
    ]
