# Generated by Django 4.2.1 on 2023-07-19 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_quote_assigned_to"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
