# Generated by Django 4.2.1 on 2023-07-24 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_quote_contract_id"),
        ("api", "0031_pricing_structure_reformat_3"),
    ]

    operations = []
