# Generated by Django 4.2.1 on 2023-07-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_pricing_structure_reformat_5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="customer_signed_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="customer_signed_title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
