# Generated by Django 4.2.1 on 2023-07-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="tenant",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="postal_code",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="tenant",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="quote",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quote_user_id",
                to="api.user",
            ),
        ),
    ]
