# Generated by Django 4.2.1 on 2023-07-28 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_account_bill_to_name_account_contact_name_and_more"),
        ("api", "0036_usersettings"),
    ]

    operations = []
