# Generated by Django 4.2.1 on 2023-07-28 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_merge_20230728_0600"),
        ("api", "0037_tenant_address_tenant_city_tenant_country_and_more"),
    ]

    operations = []
