# Generated by Django 4.2.1 on 2023-07-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_merge_20230728_0702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="alias",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
