# Generated by Django 4.2.1 on 2023-07-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_alter_user_alias_alter_user_nickname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesforcemappingmodel",
            name="config",
            field=models.JSONField(null=True),
        ),
    ]
