# Generated by Django 4.2.1 on 2023-08-01 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_alter_account_account_number"),
        ("api", "0040_user_is_monetizely_user"),
    ]

    operations = []
