# Generated by Django 4.2.1 on 2023-08-03 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_salesforcemappingmodel_config"),
        ("api", "0041_merge_20230801_1605"),
    ]

    operations = []
