# Generated by Django 4.2.1 on 2023-08-03 09:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0042_merge_20230803_0655"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("description", models.TextField(null=True)),
                ("details", models.JSONField()),
                (
                    "admin_user_id",
                    models.ForeignKey(
                        db_column="admin_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_admin_user_id",
                        to="api.user",
                    ),
                ),
                (
                    "quote_id",
                    models.ForeignKey(
                        db_column="quote_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.quote",
                    ),
                ),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "quote_audit_history",
            },
        ),
        migrations.CreateModel(
            name="ProductAuditHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("description", models.TextField(null=True)),
                ("details", models.JSONField()),
                (
                    "admin_user_id",
                    models.ForeignKey(
                        db_column="admin_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_user_id",
                        to="api.user",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "product_audit_history",
            },
        ),
        migrations.CreateModel(
            name="PricingModelHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("description", models.TextField(null=True)),
                ("details", models.JSONField()),
                (
                    "admin_user_id",
                    models.ForeignKey(
                        db_column="admin_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_model_admin_user_id",
                        to="api.user",
                    ),
                ),
                (
                    "pricing_model_id",
                    models.ForeignKey(
                        db_column="pricing_model_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pricingmodel",
                    ),
                ),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_model_audit_history",
            },
        ),
        migrations.CreateModel(
            name="PlanHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("description", models.TextField(null=True)),
                ("details", models.JSONField()),
                (
                    "admin_user_id",
                    models.ForeignKey(
                        db_column="admin_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_admin_user_id",
                        to="api.user",
                    ),
                ),
                (
                    "plan_id",
                    models.ForeignKey(
                        db_column="plan_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.plan",
                    ),
                ),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "plan_audit_history",
            },
        ),
        migrations.CreateModel(
            name="PackageHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("description", models.TextField(null=True)),
                ("details", models.JSONField()),
                (
                    "admin_user_id",
                    models.ForeignKey(
                        db_column="admin_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_admin_user_id",
                        to="api.user",
                    ),
                ),
                (
                    "package_id",
                    models.ForeignKey(
                        db_column="package_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.package",
                    ),
                ),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "package_audit_history",
            },
        ),
        migrations.CreateModel(
            name="FeatureRepositoryHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("description", models.TextField(null=True)),
                ("details", models.JSONField()),
                (
                    "admin_user_id",
                    models.ForeignKey(
                        db_column="admin_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_repository_admin_user_id",
                        to="api.user",
                    ),
                ),
                (
                    "feature_repository_id",
                    models.ForeignKey(
                        db_column="feature_repository_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.featurerepository",
                    ),
                ),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "feature_repository_audit_history",
            },
        ),
        migrations.CreateModel(
            name="FeatureHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("description", models.TextField(null=True)),
                ("details", models.JSONField()),
                (
                    "admin_user_id",
                    models.ForeignKey(
                        db_column="admin_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_admin_user_id",
                        to="api.user",
                    ),
                ),
                (
                    "feature_id",
                    models.ForeignKey(
                        db_column="feature_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.feature",
                    ),
                ),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "feature_audit_history",
            },
        ),
        migrations.CreateModel(
            name="FeatureGroupHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("description", models.TextField(null=True)),
                ("details", models.JSONField()),
                (
                    "admin_user_id",
                    models.ForeignKey(
                        db_column="admin_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_group_admin_user_id",
                        to="api.user",
                    ),
                ),
                (
                    "feature_group_id",
                    models.ForeignKey(
                        db_column="feature_group_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.featuregroup",
                    ),
                ),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "feature_group_audit_history",
            },
        ),
    ]
