# Generated by Django 4.2.1 on 2023-08-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_quotehistory_productaudithistory_pricingmodelhistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricebookrule",
            name="org_hierarchy_id",
            field=models.ForeignKey(
                db_column="org_hierarchy_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.orghierarchy",
            ),
        ),
    ]
