# Generated by Django 4.2.1 on 2023-08-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_pricebookrule_org_hierarchy_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orghierarchy",
            name="id_ext_key",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_ext_key",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="id_ext_key",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="orghierarchy",
            constraint=models.UniqueConstraint(
                fields=("id_ext_key", "tenant_id"),
                name="unique_id_ext_key_tenant_hierarchy",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("id_ext_key", "tenant_id"), name="unique_id_ext_key_tenant_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                fields=("id_ext_key", "tenant_id"), name="unique_id_ext_key_tenant_role"
            ),
        ),
    ]
