# Generated by Django 4.2.1 on 2023-08-07 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0045_alter_orghierarchy_id_ext_key_alter_user_id_ext_key_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orghierarchy",
            name="unique_id_ext_key_tenant_hierarchy",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_id_ext_key_tenant_user",
        ),
        migrations.RemoveConstraint(
            model_name="userrole",
            name="unique_id_ext_key_tenant_role",
        ),
    ]
