# Generated by Django 4.2.1 on 2023-08-17 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0049_user_cognito_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(default=255)),
                ("s3_pdf_file_path", models.CharField(default=255)),
                ("s3_html_file_path", models.CharField(default=255)),
                ("is_contract_signed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_created_by",
                        to="api.user",
                    ),
                ),
                (
                    "tenant_id",
                    models.ForeignKey(
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_updated_by",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "contract_template",
            },
        ),
    ]
