# Generated by Django 4.2.1 on 2023-08-22 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0051_contractstatus_created_by_contractstatus_updated_by_and_more"),
        ("api", "0051_pricing_structure_reformart_8"),
    ]

    operations = []
