# Generated by Django 4.2.1 on 2023-09-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0058_alter_accounthistory_admin_user_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contracttemplate",
            old_name="s3_html_file_path",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="contracttemplate",
            old_name="s3_pdf_file_path",
            new_name="s3_doc_file_path",
        ),
        migrations.RemoveField(
            model_name="contracttemplate",
            name="is_contract_signed",
        ),
        migrations.RemoveField(
            model_name="contracttemplate",
            name="title",
        ),
        migrations.AddField(
            model_name="contracttemplate",
            name="description",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)ss",
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="updated_by",
            field=models.ForeignKey(
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)ss",
                to="api.user",
            ),
        ),
    ]
