# Generated by Django 4.2.1 on 2023-09-06 08:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0059_rename_s3_html_file_path_contracttemplate_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("s3_file_path", models.TextField()),
                ("metadata", models.JSONField(null=True)),
                ("details_url", models.TextField()),
                ("files_url", models.TextField()),
                ("final_copy_uri", models.TextField()),
                ("signing_url", models.TextField()),
                ("signature_request_id", models.TextField()),
                ("expires_at", models.DateTimeField(null=True)),
                ("has_error", models.BooleanField(default=False)),
                ("is_complete", models.BooleanField(default=False)),
                ("is_declined", models.BooleanField(default=False)),
                (
                    "contract_id",
                    models.ForeignKey(
                        db_column="contract_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to="api.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "contract_signature",
            },
        ),
        migrations.CreateModel(
            name="EventDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("event_type", models.CharField()),
                ("event_time", models.DateTimeField()),
                ("event_hash", models.CharField()),
                ("event_metadata", models.JSONField()),
                (
                    "contract_signature_id",
                    models.ForeignKey(
                        db_column="contract_signature_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.contractsignature",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to="api.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "event_detail",
            },
        ),
        migrations.CreateModel(
            name="ContractSignerDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("signer_name", models.CharField(max_length=100)),
                ("signer_email_address", models.CharField(max_length=100)),
                ("order", models.IntegerField()),
                ("signature_id", models.CharField()),
                (
                    "contract_signature_id",
                    models.ForeignKey(
                        db_column="contract_signature_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.contractsignature",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to="api.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "contract_signer_details",
            },
        ),
        migrations.CreateModel(
            name="ContractSignerAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("last_viewed_at", models.DateTimeField(null=True)),
                ("last_reminded_at", models.DateTimeField(null=True)),
                ("signed_at", models.DateTimeField(null=True)),
                ("status_code", models.TextField(null=True)),
                ("error", models.TextField(null=True)),
                (
                    "contract_signer_details_id",
                    models.ForeignKey(
                        db_column="contract_signer_details_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.contractsignerdetails",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to="api.user",
                    ),
                ),
                (
                    "event_detail_id",
                    models.ForeignKey(
                        db_column="event_detail_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.eventdetail",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "contract_signer_audit_history",
            },
        ),
    ]
