# Generated by Django 4.2.1 on 2023-09-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0064_contractsignature_is_canceled"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="signer_count",
            field=models.JSONField(default=dict),
        ),
    ]
