# Generated by Django 4.2.1 on 2023-09-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0064_contractsignature_is_canceled"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractsignature",
            name="maintain_order_at",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
