# Generated by Django 4.2.1 on 2023-09-12 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0065_contractsignature_maintain_order_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractsignature",
            name="metadata",
        ),
    ]
