# Generated by Django 4.2.1 on 2023-09-13 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0061_tenantconfig"),
        ("api", "0066_remove_contractsignature_metadata"),
    ]

    operations = []
