# Generated by Django 4.2.1 on 2023-09-13 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0066_contract_s3_file_path"),
        ("api", "0067_merge_20230913_0457"),
    ]

    operations = []
