# Generated by Django 4.2.1 on 2023-09-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0071_tenant_default_deal_terms3"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="deal_term_details",
            field=models.JSONField(null=True),
        ),
    ]
