# Generated by Django 4.2.1 on 2023-09-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0071_tenant_default_deal_terms3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="customer_signed_id",
            new_name="contract_external_number",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="company_signed_id",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="contract_status_id",
        ),
        migrations.AddField(
            model_name="contract",
            name="company_signed_email",
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="customer_signed_email",
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="ContractStatus",
        ),
    ]
