# Generated by Django 4.2.1 on 2023-09-18 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0072_quote_deal_term_details"),
        (
            "api",
            "0072_rename_customer_signed_id_contract_contract_external_number_and_more",
        ),
    ]

    operations = []
