# Generated by Django 4.2.1 on 2023-09-18 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0073_merge_20230918_1306"),
        ("api", "0074_remove_contractsignature_is_canceled_and_more"),
    ]

    operations = []
