# Generated by Django 4.2.1 on 2023-09-20 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0075_merge_20230918_1317"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractsignature",
            name="s3_file_path",
        ),
    ]
