# Generated by Django 4.2.1 on 2023-09-22 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0076_remove_contractsignature_s3_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="template_id",
            field=models.ForeignKey(
                db_column="template_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_template",
                to="api.contracttemplate",
            ),
        ),
    ]
