# Generated by Django 4.2.1 on 2023-09-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0077_contract_template_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotedetails",
            name="config_details",
            field=models.JSONField(null=True),
        ),
    ]
