# Generated by Django 4.2.1 on 2023-09-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0077_contract_template_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractsignerdetails",
            name="order",
            field=models.IntegerField(null=True),
        ),
    ]
