# Generated by Django 4.2.1 on 2023-09-27 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0078_alter_contractsignerdetails_order"),
        ("api", "0079_remove_quotedetails_config_details_and_more"),
    ]

    operations = []
