# Generated by Django 4.2.1 on 2023-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0080_merge_20230927_0803"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractsignature",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("In Approval Process", "Inapprovalprocess"),
                    ("Cancelled", "Cancelled"),
                    ("Declined", "Declined"),
                    ("Activated", "Activated"),
                    ("Expired", "Expired"),
                    ("Error", "Error"),
                ],
                default="Draft",
            ),
        ),
    ]
