# Generated by Django 4.2.1 on 2023-10-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0087_contracttemplate_s3_pdf_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracttemplate",
            name="s3_pdf_file_path",
            field=models.CharField(default="Pdf not Found"),
        ),
    ]
