# Generated by Django 4.2.1 on 2023-10-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0089_fix_role_access_for_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="date_format",
            field=models.CharField(default="mm/DD/YYYY", max_length=100),
        ),
    ]
